### PR TITLE
Version 3.4.0

### PR DESCRIPTION
**Pull request by langurmonkey**

### CODE REVIEW

**Comment by BryanQuigley** [comment]
This crashes for me..

`#
# GAIA SKY CRASH REPORT
# Mon Feb 13 21:12:53 PST 2023

## STACK TRACE
java.nio.file.NoSuchFileException: /home/bryan/.var/app/de.uni_heidelberg.zah.GaiaSky/config/gaiasky/config.yaml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at gaiasky.util.GlobalResources.copyFile(GlobalResources.java:326)
	at gaiasky.desktop.GaiaSkyDesktop.initConfigFile(GaiaSkyDesktop.java:298)
	at gaiasky.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:146)


## Can't get Gaia Sky version information
## Settings.settings[.version] is null!

## JAVA INFORMATION
Java version: 17.0.1
Java runtime name: OpenJDK Runtime Environment
Java VM name: OpenJDK 64-Bit Server VM
Java VM version: 17.0.1+12
Java VM vendor: Flathub

## SYSTEM INFORMATION
CPU: AMD Ryzen 7 1700 Eight-Core Processor
AuthenticAMD Family 23 Model 1 Stepping 1
Proc ID: 0781FBFF01000711
CPU Family: 23
1 physical CPU package(s)
8 physical CPU core(s)
16 logical CPU(s)
Java used memory: 25.133056 MB
Java free memory: 2130.7392 MB
Java total memory: 2155.872256 MB
Java max memory (-Xmx): 6442.450944 MB
Total system RAM: 33577.53344 MB
 # File system root: /
   Total space: 16788.76672 MB
   Free space: 16788.672512 MB
   Usable space: 16788.672512 MB

## OS INFORMATION
OS name: GNU/Linux Freedesktop.org 21.08.18 (Flatpak runtime) build 6.1.11-1-MANJARO
OS version: 6.1.11-1-MANJARO
OS architecture: amd64
Booted: 2023-02-14T05:08:57Z
Uptime: 0 days, 00:03:55

## GL INFORMATION
## GL INFORMATION not available
`

**Comment by langurmonkey** [comment]
Dang, sorry about that. I'll get to it.

**Comment by langurmonkey** [comment]
3f17779 should fix it. Sorry about that!

**Comment by BryanQuigley** [comment]
LGTM

**Pull request merged**
